---
kind: pipeline
type: docker
name: build-x86_64-linux

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: docker.io/nixpkgs/cachix-flakes
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: CACHIX_AUTH_TOKEN
    commands:
      - "cachix use dram"
      - "cachix watch-exec dram -- nix flake check -vL"
