---
kind: pipeline
type: docker
name: check-x86_64-linux

platform:
  os: linux
  arch: amd64

steps:
  - name: "check"
    image: docker.io/nixos/nix:2.7.0
    when:
      event:
        - pull_request
    commands:
      - "echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf"
      - "echo 'max-jobs = auto' >> /etc/nix/nix.conf"
      - "nix --accept-flake-config flake check -vL"

---
kind: pipeline
type: docker
name: check-aarch64-linux

platform:
  os: linux
  arch: arm64

steps:
  - name: "check"
    image: docker.io/nixos/nix:2.7.0
    when:
      event:
        - pull_request
    commands:
      - "echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf"
      - "echo 'max-jobs = auto' >> /etc/nix/nix.conf"
      - "nix --accept-flake-config flake check -vL"

---
kind: pipeline
type: docker
name: build-x86_64-linux

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: docker.io/nixos/nix:2.7.0
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: CACHIX_AUTH_TOKEN
    commands:
      - "echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf"
      - "echo 'max-jobs = auto' >> /etc/nix/nix.conf"
      - "nix profile install nixpkgs#cachix"
      - "cachix use dram"
      - "cachix watch-exec dram -- nix flake check -vL"

trigger:
  event:
    - push
  branch:
    - main

---
kind: pipeline
type: docker
name: build-aarch64-linux

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: docker.io/nixos/nix:2.7.0
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: CACHIX_AUTH_TOKEN
    commands:
      - "echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf"
      - "echo 'max-jobs = auto' >> /etc/nix/nix.conf"
      - "nix profile install nixpkgs#cachix"
      - "cachix use dram"
      - "cachix watch-exec dram -- nix flake check -vL"

trigger:
  event:
    - push
  branch:
    - main
