name: "build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: dram
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build and upload to binary cache
      run: nix flake check -vL
