name: "nix flake check"
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    environment: cachix

    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0

    - name: Cache nix store
      uses: actions/cache@v2
      env:
        cache-name: cache-nix-store
      with:
        path: [ "/nix/store", "/nix/var/nix/db" ]
        key: binary-cache-v5

    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - uses: cachix/cachix-action@v8
      if: ${{ github.event_name == 'push' }}
      with:
        name: dram
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix flake check -vL
    - run: nix flake archive
